name: Publish to JSR

on: push

permissions: write-all

jobs:
  codegen:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v2.x
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@main
        with:
          github_token: ${{ github.token }}
      - name: Generate code
        run: buf generate
      - name: Genrate Barrel file
        run: deno run --allow-read --allow-write bin/gen-barrel.ts
      - name: Set Package Version
        run: |
          TAG_VERSION=$(git -C lattice-sdk-cpp describe --tags --abbrev=0 | sed 's/^v//')
          sed -i "s/__PACKAGE_VERSION__/$TAG_VERSION/g" src/deno.json
      - name: Copy license & README
        run: |
          cp lattice-sdk-cpp/LICENSE.md src
          cp lattice-sdk-cpp/README.md src
      - name: Upload TypeScript code
        uses: actions/upload-artifact@v4
        with:
          name: ts_code
          path: src

  publish-jsr:
    runs-on: ubuntu-24.04
    needs: codegen
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download TypeScript code
        uses: actions/download-artifact@v4
        with:
          name: ts_code
      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v2.x
      - name: Publish to JSR
        run: deno publish
